# # # # # # # # # # # # # # # # # #
# # # DO NOT EDIT THIS FILE # # # #
# # # # # # # # # # # # # # # # # #

FILE = psi
LATEX = latex -enable-write18 -shell-escape -interaction=nonstopmode
PDFLATEX = pdflatex -enable-write18 -shell-escape -interaction=nonstopmode
DVIPS = dvips
PS2PDF = ps2pdf
INDEX = makeindex
VIEWER = xdg-open

all: complete

quick:
	$(LATEX) "$(FILE).tex"
	$(DVIPS) "$(FILE).dvi"
	$(PS2PDF) "$(FILE).ps"

complete:
	$(LATEX) "$(FILE).tex"
	$(INDEX) "$(FILE).idx"
	$(LATEX) "$(FILE).tex"
	$(LATEX) "$(FILE).tex"
	$(DVIPS) "$(FILE).dvi"
	$(PS2PDF) "$(FILE).ps"

view:
	$(VIEWER) "$(FILE).pdf" &

# All clean commands will preserve output
.PHONY : clean
clean:
	$(RM) *.dvi *.ps

distclean:
	$(RM) *.aux *.bbl *.bcf *.blg *.dvi *.lof *.log *.fdb_latexmk *.fls *.idx *.ilg *.ind *.out *.ps *.run.xml *.thm *.toc

